accounts:
  - name: dummy
    mnemonic: "expect crisp umbrella hospital firm exhibit future size slot update blood deliver fat happy ghost visa recall usual path purity junior ring ordinary stove"
  - name: alice
    coins: ["2000000000000000000tkyve"]
    mnemonic: "worry grief loyal smoke pencil arrow trap focus high pioneer tomato hedgehog essence purchase dove pond knee custom phone gentle sunset addict mother fabric"
  - name: bob
    coins: ["1000000000000000000tkyve"]
    mnemonic: "crash sick toilet stumble join cash erode glory door weird diagram away lizard solid segment apple urge joy annual able tank define candy demise"
  - name: charlie
    coins: ["1000000000000000000tkyve"]
    mnemonic: "shoot inject fragile width trend satisfy army enact volcano crowd message strike true divorce search rich office shoulder sport relax rhythm symbol gadget size"
  - name: faucet
    coins: ["1000000000000000000tkyve"]
    mnemonic: "open home share route party lake room solution quantum pact model avocado humor dilemma review desert turtle total humor produce rate keen eagle fee"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins: ["1000000000000000tkyve"]
genesis:
  chain_id: "kyve-local"
  app_state:
    staking:
      params:
        bond_denom: "tkyve"
    gov:
      voting_params:
        # 1 day
        voting_period: "120s"
        # 30 minutes
        expedited_voting_period: "1800s"
      deposit_params:
          min_deposit: [
            {
              denom: "tkyve",
              # 50 $KYVE
              amount: "50_000_000_000"
            }
          ]
          # 5 minutes
          max_deposit_period: "300s"
          min_expedited_deposit: [
            {
              denom: "tkyve",
              # 250 $KYVE
              amount: "250_000_000_000"
            }
          ]
    pool:
      pool_count: "1"
      pool_list: [
        {
          id: "0",
          name: "Avalanche // C-Chain",
          runtime: "@kyve/evm",
          logo: "E3jXAOeJ3El7HQgOf_NtSOwVE7Sd0M4g4bYqjCBH9CU",
          config: "{\"rpc\":\"https://api.avax.network/ext/bc/C/rpc\",\"github\":\"https://github.com/KYVENetwork/evm\"}",

          start_key: "0",
          current_key: "",
          current_value: "",
          current_height: "0",

          total_bundles: "0",

          upload_interval: "60",
          operating_cost: "2500000000",
          min_stake: "100000000000",
          max_bundle_size: "100",

          paused: false,

          funders: [],
          total_funds: "0",

          protocol:
            version: "1.7.0"
            binaries: "{\"macos\":\"https://github.com/kyve-org/evm/releases/download/v1.0.5/kyve-evm-macos.zip\"}"
            last_upgrade: "0",
          upgrade_plan:
            version: ""
            binaries: ""
            scheduled_at: "0"
            duration: "0",
        },
      ]
    delegation:
      params:
        unbonding_delegation_time: 10
    stakers:
      params:
        commission_change_time: 10
validator:
  name: alice
  staked: "1000000000000000tkyve"
build:
  main: "cmd/kyved"