// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kyve/stakers/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// vote_slash ...
	VoteSlash string `protobuf:"bytes,1,opt,name=vote_slash,json=voteSlash,proto3" json:"vote_slash,omitempty"`
	// upload_slash ...
	UploadSlash string `protobuf:"bytes,2,opt,name=upload_slash,json=uploadSlash,proto3" json:"upload_slash,omitempty"`
	// timeout_slash ...
	TimeoutSlash string `protobuf:"bytes,3,opt,name=timeout_slash,json=timeoutSlash,proto3" json:"timeout_slash,omitempty"`
	// unbonding_staking_time ...
	UnbondingStakingTime uint64 `protobuf:"varint,4,opt,name=unbonding_staking_time,json=unbondingStakingTime,proto3" json:"unbonding_staking_time,omitempty"`
	// commission_change_time ...
	CommissionChangeTime uint64 `protobuf:"varint,5,opt,name=commission_change_time,json=commissionChangeTime,proto3" json:"commission_change_time,omitempty"`
	// commission_change_time ...
	LeavePoolTime uint64 `protobuf:"varint,6,opt,name=leave_pool_time,json=leavePoolTime,proto3" json:"leave_pool_time,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_405cabd7005fc18b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVoteSlash() string {
	if m != nil {
		return m.VoteSlash
	}
	return ""
}

func (m *Params) GetUploadSlash() string {
	if m != nil {
		return m.UploadSlash
	}
	return ""
}

func (m *Params) GetTimeoutSlash() string {
	if m != nil {
		return m.TimeoutSlash
	}
	return ""
}

func (m *Params) GetUnbondingStakingTime() uint64 {
	if m != nil {
		return m.UnbondingStakingTime
	}
	return 0
}

func (m *Params) GetCommissionChangeTime() uint64 {
	if m != nil {
		return m.CommissionChangeTime
	}
	return 0
}

func (m *Params) GetLeavePoolTime() uint64 {
	if m != nil {
		return m.LeavePoolTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "kyve.stakers.v1beta1.Params")
}

func init() { proto.RegisterFile("kyve/stakers/v1beta1/params.proto", fileDescriptor_405cabd7005fc18b) }

var fileDescriptor_405cabd7005fc18b = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd1, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0x06, 0xf0, 0x76, 0xce, 0xc1, 0xe2, 0x86, 0x30, 0x86, 0x0c, 0xc1, 0xba, 0x29, 0xc8, 0x0e,
	0xd2, 0x30, 0xf4, 0xe4, 0x51, 0xd1, 0x8b, 0x20, 0x63, 0x13, 0x41, 0x2f, 0x25, 0xed, 0x42, 0x1b,
	0xd6, 0xe4, 0x5f, 0x9a, 0xb4, 0xba, 0x47, 0xf0, 0xe6, 0xd1, 0xa3, 0x8f, 0xe3, 0x71, 0x47, 0x8f,
	0xb2, 0xbe, 0x88, 0x24, 0x29, 0xf3, 0xd4, 0xf2, 0x7d, 0xbf, 0x0f, 0x42, 0x82, 0x46, 0xcb, 0x55,
	0x49, 0xb1, 0x54, 0x64, 0x49, 0x73, 0x89, 0xcb, 0x49, 0x48, 0x15, 0x99, 0xe0, 0x8c, 0xe4, 0x84,
	0x4b, 0x3f, 0xcb, 0x41, 0x41, 0xaf, 0xaf, 0x89, 0x5f, 0x13, 0xbf, 0x26, 0x87, 0xfd, 0x18, 0x62,
	0x30, 0x00, 0xeb, 0x3f, 0x6b, 0x4f, 0xde, 0x1b, 0xa8, 0x35, 0x35, 0xe3, 0xde, 0x11, 0x42, 0x25,
	0x28, 0x1a, 0xc8, 0x94, 0xc8, 0x64, 0xe0, 0x0e, 0xdd, 0x71, 0x7b, 0xd6, 0xd6, 0xc9, 0x5c, 0x07,
	0xbd, 0x11, 0xea, 0x14, 0x59, 0x0a, 0x64, 0x51, 0x83, 0x86, 0x01, 0x7b, 0x36, 0xb3, 0xe4, 0x14,
	0x75, 0x15, 0xe3, 0x14, 0x0a, 0x55, 0x9b, 0x1d, 0x63, 0x3a, 0x75, 0x68, 0xd1, 0x25, 0x3a, 0x28,
	0x44, 0x08, 0x62, 0xc1, 0x44, 0x1c, 0xe8, 0x43, 0xea, 0xaf, 0x16, 0x83, 0xe6, 0xd0, 0x1d, 0x37,
	0x67, 0xfd, 0x6d, 0x3b, 0xb7, 0xe5, 0x23, 0xe3, 0x54, 0xaf, 0x22, 0xe0, 0x9c, 0x49, 0xc9, 0x40,
	0x04, 0x51, 0x42, 0x44, 0x4c, 0xed, 0x6a, 0xd7, 0xae, 0xfe, 0xdb, 0x1b, 0x53, 0x9a, 0xd5, 0x19,
	0xda, 0x4f, 0x29, 0x29, 0x69, 0x90, 0x01, 0xa4, 0x96, 0xb7, 0x0c, 0xef, 0x9a, 0x78, 0x0a, 0x90,
	0x6a, 0x77, 0xd5, 0xfc, 0xfc, 0x3a, 0x76, 0xae, 0xef, 0xbe, 0x37, 0x9e, 0xbb, 0xde, 0x78, 0xee,
	0xef, 0xc6, 0x73, 0x3f, 0x2a, 0xcf, 0x59, 0x57, 0x9e, 0xf3, 0x53, 0x79, 0xce, 0xcb, 0x79, 0xcc,
	0x54, 0x52, 0x84, 0x7e, 0x04, 0x1c, 0xdf, 0x3f, 0x3f, 0xdd, 0x3e, 0x50, 0xf5, 0x0a, 0xf9, 0x12,
	0x47, 0x09, 0x61, 0x02, 0xbf, 0x6d, 0x9f, 0x43, 0xad, 0x32, 0x2a, 0xc3, 0x96, 0xb9, 0xda, 0x8b,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xee, 0x95, 0xc5, 0xab, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LeavePoolTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LeavePoolTime))
		i--
		dAtA[i] = 0x30
	}
	if m.CommissionChangeTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CommissionChangeTime))
		i--
		dAtA[i] = 0x28
	}
	if m.UnbondingStakingTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnbondingStakingTime))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TimeoutSlash) > 0 {
		i -= len(m.TimeoutSlash)
		copy(dAtA[i:], m.TimeoutSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TimeoutSlash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.UploadSlash) > 0 {
		i -= len(m.UploadSlash)
		copy(dAtA[i:], m.UploadSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.UploadSlash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoteSlash) > 0 {
		i -= len(m.VoteSlash)
		copy(dAtA[i:], m.VoteSlash)
		i = encodeVarintParams(dAtA, i, uint64(len(m.VoteSlash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VoteSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.UploadSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.TimeoutSlash)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.UnbondingStakingTime != 0 {
		n += 1 + sovParams(uint64(m.UnbondingStakingTime))
	}
	if m.CommissionChangeTime != 0 {
		n += 1 + sovParams(uint64(m.CommissionChangeTime))
	}
	if m.LeavePoolTime != 0 {
		n += 1 + sovParams(uint64(m.LeavePoolTime))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutSlash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeoutSlash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStakingTime", wireType)
			}
			m.UnbondingStakingTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingStakingTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionChangeTime", wireType)
			}
			m.CommissionChangeTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissionChangeTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeavePoolTime", wireType)
			}
			m.LeavePoolTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeavePoolTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
