// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kyve/query/v1beta1/stakers.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/KYVENetwork/chain/x/stakers/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryStakersRequest is the request type for the Query/Stakers RPC method.
type QueryStakersRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryStakersRequest) Reset()         { *m = QueryStakersRequest{} }
func (m *QueryStakersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakersRequest) ProtoMessage()    {}
func (*QueryStakersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{0}
}
func (m *QueryStakersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakersRequest.Merge(m, src)
}
func (m *QueryStakersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakersRequest proto.InternalMessageInfo

func (m *QueryStakersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryStakersResponse is the response type for the Query/Stakers RPC method.
type QueryStakersResponse struct {
	// stakers ...
	Stakers []FullStaker `protobuf:"bytes,1,rep,name=stakers,proto3" json:"stakers"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryStakersResponse) Reset()         { *m = QueryStakersResponse{} }
func (m *QueryStakersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakersResponse) ProtoMessage()    {}
func (*QueryStakersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{1}
}
func (m *QueryStakersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakersResponse.Merge(m, src)
}
func (m *QueryStakersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakersResponse proto.InternalMessageInfo

func (m *QueryStakersResponse) GetStakers() []FullStaker {
	if m != nil {
		return m.Stakers
	}
	return nil
}

func (m *QueryStakersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryStakerRequest is the request type for the Query/Staker RPC method.
type QueryStakerRequest struct {
	// address ...
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryStakerRequest) Reset()         { *m = QueryStakerRequest{} }
func (m *QueryStakerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakerRequest) ProtoMessage()    {}
func (*QueryStakerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{2}
}
func (m *QueryStakerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakerRequest.Merge(m, src)
}
func (m *QueryStakerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakerRequest proto.InternalMessageInfo

func (m *QueryStakerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryStakerResponse is the response type for the Query/Staker RPC method.
type QueryStakerResponse struct {
	// staker ...
	Staker FullStaker `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker"`
}

func (m *QueryStakerResponse) Reset()         { *m = QueryStakerResponse{} }
func (m *QueryStakerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakerResponse) ProtoMessage()    {}
func (*QueryStakerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{3}
}
func (m *QueryStakerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakerResponse.Merge(m, src)
}
func (m *QueryStakerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakerResponse proto.InternalMessageInfo

func (m *QueryStakerResponse) GetStaker() FullStaker {
	if m != nil {
		return m.Staker
	}
	return FullStaker{}
}

// QueryStakersByPoolRequest is the request type for the Query/Staker RPC method.
type QueryStakersByPoolRequest struct {
	// pool_id ...
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (m *QueryStakersByPoolRequest) Reset()         { *m = QueryStakersByPoolRequest{} }
func (m *QueryStakersByPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakersByPoolRequest) ProtoMessage()    {}
func (*QueryStakersByPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{4}
}
func (m *QueryStakersByPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakersByPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakersByPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakersByPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakersByPoolRequest.Merge(m, src)
}
func (m *QueryStakersByPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakersByPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakersByPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakersByPoolRequest proto.InternalMessageInfo

func (m *QueryStakersByPoolRequest) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

// QueryStakersByPoolResponse is the response type for the Query/Staker RPC method.
type QueryStakersByPoolResponse struct {
	// stakers ...
	Stakers []StakerPoolResponse `protobuf:"bytes,1,rep,name=stakers,proto3" json:"stakers"`
}

func (m *QueryStakersByPoolResponse) Reset()         { *m = QueryStakersByPoolResponse{} }
func (m *QueryStakersByPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakersByPoolResponse) ProtoMessage()    {}
func (*QueryStakersByPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{5}
}
func (m *QueryStakersByPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakersByPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakersByPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakersByPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakersByPoolResponse.Merge(m, src)
}
func (m *QueryStakersByPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakersByPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakersByPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakersByPoolResponse proto.InternalMessageInfo

func (m *QueryStakersByPoolResponse) GetStakers() []StakerPoolResponse {
	if m != nil {
		return m.Stakers
	}
	return nil
}

// StakerPoolResponse ...
type StakerPoolResponse struct {
	// staker ...
	Staker *FullStaker `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty"`
	// valaccount ...
	Valaccount *types.Valaccount `protobuf:"bytes,2,opt,name=valaccount,proto3" json:"valaccount,omitempty"`
}

func (m *StakerPoolResponse) Reset()         { *m = StakerPoolResponse{} }
func (m *StakerPoolResponse) String() string { return proto.CompactTextString(m) }
func (*StakerPoolResponse) ProtoMessage()    {}
func (*StakerPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6aa31a681566da33, []int{6}
}
func (m *StakerPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakerPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakerPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakerPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakerPoolResponse.Merge(m, src)
}
func (m *StakerPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *StakerPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakerPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakerPoolResponse proto.InternalMessageInfo

func (m *StakerPoolResponse) GetStaker() *FullStaker {
	if m != nil {
		return m.Staker
	}
	return nil
}

func (m *StakerPoolResponse) GetValaccount() *types.Valaccount {
	if m != nil {
		return m.Valaccount
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryStakersRequest)(nil), "kyve.query.v1beta1.QueryStakersRequest")
	proto.RegisterType((*QueryStakersResponse)(nil), "kyve.query.v1beta1.QueryStakersResponse")
	proto.RegisterType((*QueryStakerRequest)(nil), "kyve.query.v1beta1.QueryStakerRequest")
	proto.RegisterType((*QueryStakerResponse)(nil), "kyve.query.v1beta1.QueryStakerResponse")
	proto.RegisterType((*QueryStakersByPoolRequest)(nil), "kyve.query.v1beta1.QueryStakersByPoolRequest")
	proto.RegisterType((*QueryStakersByPoolResponse)(nil), "kyve.query.v1beta1.QueryStakersByPoolResponse")
	proto.RegisterType((*StakerPoolResponse)(nil), "kyve.query.v1beta1.StakerPoolResponse")
}

func init() { proto.RegisterFile("kyve/query/v1beta1/stakers.proto", fileDescriptor_6aa31a681566da33) }

var fileDescriptor_6aa31a681566da33 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0x87, 0x33, 0x6d, 0x49, 0x70, 0xaa, 0x97, 0xb1, 0x60, 0x5d, 0x75, 0x0d, 0xab, 0x24, 0xa1,
	0xd8, 0x19, 0x1a, 0xff, 0x9c, 0x44, 0x24, 0x68, 0x44, 0x04, 0xa9, 0x5b, 0x28, 0x28, 0x48, 0x98,
	0x24, 0xc3, 0x76, 0xc9, 0x76, 0x67, 0x9b, 0x99, 0x44, 0x43, 0xe9, 0x41, 0x2f, 0xde, 0x44, 0xf0,
	0x03, 0x78, 0xf2, 0x9b, 0x78, 0xe8, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0xe2, 0x07, 0x91, 0x9d, 0x99,
	0xad, 0xbb, 0xe9, 0xd6, 0xad, 0xb7, 0xd9, 0xdd, 0xf7, 0x99, 0x79, 0x7e, 0xef, 0xbe, 0x0c, 0xac,
	0x0e, 0x26, 0x63, 0x46, 0xf6, 0x46, 0x6c, 0x38, 0x21, 0xe3, 0x8d, 0x2e, 0x93, 0x74, 0x83, 0x08,
	0x49, 0x07, 0x6c, 0x28, 0x70, 0x34, 0xe4, 0x92, 0x23, 0x14, 0x57, 0x60, 0x55, 0x81, 0x4d, 0x85,
	0xb5, 0xd6, 0xe3, 0x62, 0x97, 0x0b, 0xd2, 0xa5, 0x62, 0x1e, 0x8e, 0xa8, 0xe7, 0x87, 0x54, 0xfa,
	0x3c, 0xd4, 0xbc, 0xb5, 0xe2, 0x71, 0x8f, 0xab, 0x25, 0x89, 0x57, 0xe6, 0xed, 0x55, 0x8f, 0x73,
	0x2f, 0x60, 0x84, 0x46, 0x3e, 0xa1, 0x61, 0xc8, 0xa5, 0x42, 0xcc, 0x99, 0x96, 0x9d, 0x63, 0xa5,
	0x0d, 0xf4, 0x77, 0x47, 0x7d, 0x37, 0x9e, 0xf9, 0xde, 0xce, 0x6b, 0x78, 0xf1, 0x45, 0x8c, 0x6c,
	0xe9, 0xb7, 0x2e, 0xdb, 0x1b, 0x31, 0x21, 0x51, 0x1b, 0xc2, 0xbf, 0x8a, 0xab, 0xa0, 0x0a, 0x1a,
	0xcb, 0xcd, 0x1a, 0xd6, 0x79, 0x70, 0x9c, 0x27, 0x1b, 0x15, 0x6f, 0x52, 0x8f, 0x19, 0xd6, 0x4d,
	0x91, 0xce, 0x17, 0x00, 0x57, 0xb2, 0xfb, 0x8b, 0x88, 0x87, 0x82, 0xa1, 0x07, 0xb0, 0x62, 0x44,
	0x56, 0x41, 0x75, 0xb1, 0xb1, 0xdc, 0xb4, 0xf1, 0xc9, 0x0e, 0xe2, 0xf6, 0x28, 0x08, 0x34, 0xd9,
	0x5a, 0x3a, 0xfc, 0x79, 0xbd, 0xe4, 0x26, 0x10, 0x7a, 0x92, 0x11, 0x5c, 0x50, 0x82, 0xf5, 0x42,
	0x41, 0x7d, 0x78, 0xc6, 0x10, 0x43, 0x94, 0x12, 0x4c, 0xf2, 0xaf, 0xc2, 0x0a, 0xed, 0xf7, 0x87,
	0x4c, 0x08, 0x15, 0xfe, 0x9c, 0x9b, 0x3c, 0x3a, 0x5b, 0x99, 0x86, 0x1d, 0xe7, 0xb9, 0x0f, 0xcb,
	0x5a, 0xcd, 0x34, 0xeb, 0x6c, 0x71, 0x0c, 0xe3, 0xdc, 0x81, 0x97, 0xd3, 0x5d, 0x6a, 0x4d, 0x36,
	0x39, 0x0f, 0x12, 0x97, 0x4b, 0xb0, 0x12, 0x71, 0x1e, 0x74, 0xfc, 0xbe, 0xda, 0x7b, 0xc9, 0x2d,
	0xc7, 0x8f, 0x4f, 0xfb, 0x4e, 0x1f, 0x5a, 0x79, 0x94, 0x31, 0x6a, 0xcf, 0x77, 0xb8, 0x96, 0xa7,
	0xa4, 0xd9, 0x34, 0x38, 0xd7, 0x69, 0xe7, 0x23, 0x80, 0xe8, 0x64, 0x15, 0xba, 0xf7, 0x7f, 0x81,
	0x93, 0xa8, 0xe8, 0x21, 0x84, 0x63, 0x1a, 0xd0, 0x5e, 0x8f, 0x8f, 0x42, 0x69, 0x7e, 0x5c, 0x55,
	0xb3, 0xc9, 0x64, 0x26, 0xf4, 0xf6, 0x71, 0x9d, 0x9b, 0x62, 0x9a, 0xdf, 0x16, 0xe1, 0xf9, 0x74,
	0x6e, 0xf4, 0x0e, 0xc0, 0x4a, 0xb2, 0xae, 0xe7, 0x69, 0xe4, 0x4c, 0xb8, 0xd5, 0x28, 0x2e, 0xd4,
	0x49, 0x9d, 0x1b, 0xef, 0xbf, 0xff, 0xfe, 0xbc, 0x70, 0x0d, 0x5d, 0x21, 0xa7, 0xdf, 0x02, 0xe8,
	0x03, 0x80, 0x65, 0x0d, 0xa2, 0x5a, 0xc1, 0xce, 0x89, 0x41, 0xbd, 0xb0, 0xce, 0x08, 0xdc, 0x52,
	0x02, 0x35, 0x74, 0xf3, 0x74, 0x01, 0xb2, 0x6f, 0xe6, 0xf3, 0x00, 0x7d, 0x05, 0xf0, 0x42, 0x66,
	0x22, 0xd0, 0x7a, 0x51, 0xd4, 0xcc, 0xbc, 0x59, 0xf8, 0xac, 0xe5, 0x46, 0xef, 0xae, 0xd2, 0x23,
	0x68, 0xfd, 0x1f, 0xfd, 0xe9, 0x74, 0x27, 0x9d, 0x78, 0x6a, 0xc9, 0xbe, 0x19, 0xe5, 0x83, 0xd6,
	0xa3, 0xc3, 0xa9, 0x0d, 0x8e, 0xa6, 0x36, 0xf8, 0x35, 0xb5, 0xc1, 0xa7, 0x99, 0x5d, 0x3a, 0x9a,
	0xd9, 0xa5, 0x1f, 0x33, 0xbb, 0xf4, 0x6a, 0xcd, 0xf3, 0xe5, 0xce, 0xa8, 0x8b, 0x7b, 0x7c, 0x97,
	0x3c, 0x7b, 0xb9, 0xfd, 0xf8, 0x39, 0x93, 0x6f, 0xf8, 0x70, 0x40, 0x7a, 0x3b, 0xd4, 0x0f, 0xc9,
	0x5b, 0x73, 0x82, 0x9c, 0x44, 0x4c, 0x74, 0xcb, 0xea, 0x1a, 0xbb, 0xfd, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x6e, 0xfd, 0x01, 0xa2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryStakersClient is the client API for QueryStakers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryStakersClient interface {
	// Stakers queries for all stakers.
	Stakers(ctx context.Context, in *QueryStakersRequest, opts ...grpc.CallOption) (*QueryStakersResponse, error)
	// Staker queries for all stakers.
	Staker(ctx context.Context, in *QueryStakerRequest, opts ...grpc.CallOption) (*QueryStakerResponse, error)
	// StakersByPool queries for all stakers that are currently participating in the given pool
	StakersByPool(ctx context.Context, in *QueryStakersByPoolRequest, opts ...grpc.CallOption) (*QueryStakersByPoolResponse, error)
}

type queryStakersClient struct {
	cc grpc1.ClientConn
}

func NewQueryStakersClient(cc grpc1.ClientConn) QueryStakersClient {
	return &queryStakersClient{cc}
}

func (c *queryStakersClient) Stakers(ctx context.Context, in *QueryStakersRequest, opts ...grpc.CallOption) (*QueryStakersResponse, error) {
	out := new(QueryStakersResponse)
	err := c.cc.Invoke(ctx, "/kyve.query.v1beta1.QueryStakers/Stakers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryStakersClient) Staker(ctx context.Context, in *QueryStakerRequest, opts ...grpc.CallOption) (*QueryStakerResponse, error) {
	out := new(QueryStakerResponse)
	err := c.cc.Invoke(ctx, "/kyve.query.v1beta1.QueryStakers/Staker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryStakersClient) StakersByPool(ctx context.Context, in *QueryStakersByPoolRequest, opts ...grpc.CallOption) (*QueryStakersByPoolResponse, error) {
	out := new(QueryStakersByPoolResponse)
	err := c.cc.Invoke(ctx, "/kyve.query.v1beta1.QueryStakers/StakersByPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryStakersServer is the server API for QueryStakers service.
type QueryStakersServer interface {
	// Stakers queries for all stakers.
	Stakers(context.Context, *QueryStakersRequest) (*QueryStakersResponse, error)
	// Staker queries for all stakers.
	Staker(context.Context, *QueryStakerRequest) (*QueryStakerResponse, error)
	// StakersByPool queries for all stakers that are currently participating in the given pool
	StakersByPool(context.Context, *QueryStakersByPoolRequest) (*QueryStakersByPoolResponse, error)
}

// UnimplementedQueryStakersServer can be embedded to have forward compatible implementations.
type UnimplementedQueryStakersServer struct {
}

func (*UnimplementedQueryStakersServer) Stakers(ctx context.Context, req *QueryStakersRequest) (*QueryStakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stakers not implemented")
}
func (*UnimplementedQueryStakersServer) Staker(ctx context.Context, req *QueryStakerRequest) (*QueryStakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Staker not implemented")
}
func (*UnimplementedQueryStakersServer) StakersByPool(ctx context.Context, req *QueryStakersByPoolRequest) (*QueryStakersByPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakersByPool not implemented")
}

func RegisterQueryStakersServer(s grpc1.Server, srv QueryStakersServer) {
	s.RegisterService(&_QueryStakers_serviceDesc, srv)
}

func _QueryStakers_Stakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryStakersServer).Stakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kyve.query.v1beta1.QueryStakers/Stakers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryStakersServer).Stakers(ctx, req.(*QueryStakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryStakers_Staker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryStakersServer).Staker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kyve.query.v1beta1.QueryStakers/Staker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryStakersServer).Staker(ctx, req.(*QueryStakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryStakers_StakersByPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakersByPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryStakersServer).StakersByPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kyve.query.v1beta1.QueryStakers/StakersByPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryStakersServer).StakersByPool(ctx, req.(*QueryStakersByPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryStakers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kyve.query.v1beta1.QueryStakers",
	HandlerType: (*QueryStakersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stakers",
			Handler:    _QueryStakers_Stakers_Handler,
		},
		{
			MethodName: "Staker",
			Handler:    _QueryStakers_Staker_Handler,
		},
		{
			MethodName: "StakersByPool",
			Handler:    _QueryStakers_StakersByPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyve/query/v1beta1/stakers.proto",
}

func (m *QueryStakersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStakers(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStakers(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Stakers) > 0 {
		for iNdEx := len(m.Stakers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stakers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStakers(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Staker.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStakers(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryStakersByPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakersByPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakersByPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolId != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakersByPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakersByPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakersByPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Stakers) > 0 {
		for iNdEx := len(m.Stakers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stakers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStakers(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StakerPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakerPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakerPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Valaccount != nil {
		{
			size, err := m.Valaccount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStakers(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Staker != nil {
		{
			size, err := m.Staker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStakers(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStakers(dAtA []byte, offset int, v uint64) int {
	offset -= sovStakers(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryStakersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovStakers(uint64(l))
	}
	return n
}

func (m *QueryStakersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stakers) > 0 {
		for _, e := range m.Stakers {
			l = e.Size()
			n += 1 + l + sovStakers(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovStakers(uint64(l))
	}
	return n
}

func (m *QueryStakerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	return n
}

func (m *QueryStakerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Staker.Size()
	n += 1 + l + sovStakers(uint64(l))
	return n
}

func (m *QueryStakersByPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovStakers(uint64(m.PoolId))
	}
	return n
}

func (m *QueryStakersByPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stakers) > 0 {
		for _, e := range m.Stakers {
			l = e.Size()
			n += 1 + l + sovStakers(uint64(l))
		}
	}
	return n
}

func (m *StakerPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Staker != nil {
		l = m.Staker.Size()
		n += 1 + l + sovStakers(uint64(l))
	}
	if m.Valaccount != nil {
		l = m.Valaccount.Size()
		n += 1 + l + sovStakers(uint64(l))
	}
	return n
}

func sovStakers(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStakers(x uint64) (n int) {
	return sovStakers(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryStakersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stakers = append(m.Stakers, FullStaker{})
			if err := m.Stakers[len(m.Stakers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Staker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakersByPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakersByPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakersByPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakersByPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakersByPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakersByPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stakers = append(m.Stakers, StakerPoolResponse{})
			if err := m.Stakers[len(m.Stakers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakerPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakerPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakerPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Staker == nil {
				m.Staker = &FullStaker{}
			}
			if err := m.Staker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valaccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Valaccount == nil {
				m.Valaccount = &types.Valaccount{}
			}
			if err := m.Valaccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStakers(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStakers
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStakers
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStakers
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStakers        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStakers          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStakers = fmt.Errorf("proto: unexpected end of group")
)
